### ISSUE TITLE
List of fixes needed for Statusbar

### ISSUE THREAD

**Issue by rgleason** [rgleason/statusbar_pi#14]
Preferences menu is not showing correctly.
Also the font and size have to be reset.

FIXED.  Closing this post

**Comment by rgleason** [comment]
Perhaps this was caused by the isnan fixes required to get it to build?  That is the only change except updating TP Template
https://github.com/rgleason/statusbar_pi/commits/master

**Comment by rgleason** [comment]
This is beginning to work better but these need to be fixed.
1.  Text transparency isn't working.
2.  Multiline text repeats from the beginning so Lat Long is shown twice.
3. Resizing to show the entire text entry area is not yet possible.
4. There is a mono-spaced problem with the text display.
5. The background color should resize to the the text size but a little larger.
6. We should be able to set the line spacing for multiple lines.

![multiline](https://user-images.githubusercontent.com/2363959/211158027-f420a06e-c3ec-4e58-a0e6-60115c38d86c.png)
![Default](https://user-images.githubusercontent.com/2363959/211158029-32fab010-c3b0-4a36-bd2a-a977caac7a5d.png)

**Comment by Carl-Port** [comment]
Hi again

I'm sorry to be once again the carrier of a problem in the Statusbar Plugin:

I noticed that the code (%L) referring to "Ship Heading Magnetic" is not displaying this information, only the code for the "Ship Heading True" function is currently operational.

Considering that simultaneously being activated the dashboard, this other plugin would be fully functional with regard to this function specifically.

Thanks again and all the best.
