### ISSUE TITLE
Geographical Coordinates  Discrepancies

### ISSUE THREAD

**Issue by Carl-Port** [rgleason/statusbar_pi#15]
Statusbar

I don't know if this problem has been reported previously, as I've included this report in the posts regarding the new beta version of [OpenCPN](https://www.cruisersforum.com/forums/tags/opencpn.html), but if it hasn't come to your attention, I'm repeating the text just below as well as the image.

Apparently that old problem still exists:

The geographic coordinates in Degree, Minutes, and Seconds show a one-minute difference more in the Statusbar [plugin](https://www.cruisersforum.com/forums/tags/plugin.html), relative to the coordinates shown in the standard statusbar.

String in use with 3 lines:

%d %t %z \n Ship %02A° %02B' %02.3C" %D %03E° %02F' %02.3G" %H \n HDG %03.02a° HDT %03.02K HDM %03.02L COG %03.02J SOG %2.02I

Well, I tested with two different [GPS](https://www.cruisersforum.com/forums/tags/gps.html) using 3 different [software](https://www.cruisersforum.com/forums/tags/software.html) and, the correct answer is that the most approximate position is that of the standard statusbar of [OpenCPN](https://www.cruisersforum.com/forums/tags/opencpn.html), however the error in the [Plugin](https://www.cruisersforum.com/forums/tags/plugin.html) does not restrict only to the addition of a minute, because for any position, when reaching 60', in fact the [plugin](https://www.cruisersforum.com/forums/tags/plugin.html) or any other system, should increase 1° and restart showing 00', and obviously similar situation should be repeated in the refers to the Seconds, ie 00".

This error was noticed in Latitude, so I don't know if this is also occurring in Longitude, but it's likely to be, and I also haven't checked whether this error repeats in the data for Seconds.

Although this seems to be only a detail, as everyone can assess, such a problem can lead to catastrophic errors, after all the error of 1' adds to the error of 1°, which of course is no small thing, because depending on the latitude this error of only 1' would amount to one nautical mile.

Although this seems obvious, I just point out that in the scale of the numbering of minutes and seconds, both in Longitude and Latitude, in this case should not appear the number 60' or 60", but only go up to 59'or 59", and the next numbering again would be 00' or 00".

In Longitude, the numbering limit reaching exactly 180°, only E or W would be changed.

Thank you and I hope this can help.

Carl

![GPS Position in Statusbar](https://user-images.githubusercontent.com/83961934/221911247-c7f6c6f8-ef52-4f33-a4a8-5f3e501b09c8.jpg)

![GPS Position in Statusbar](https://user-images.githubusercontent.com/83961934/221912679-59c2a31e-4a1b-41e2-b3b3-c65fc2e0781d.jpg)

**Comment by rgleason** [comment]
This should be fixed by  https://github.com/rgleason/statusbar_pi/pull/19
It will be pushed up to PIM soon. Please test and close this if it is fixed. Thanks!
