### ISSUE TITLE
Language and Background Problems 

### ISSUE THREAD

**Issue by Carl-Port** [rgleason/statusbar_pi#6]
Hi

I hope everyone is well and in good health.

Well, I tested the new version, in English and Portuguese language, as well as Brazilian Portuguese, and only in English the string works perfectly, because in the other languages, only the first line appears, that is, multiple lines only appear in English, But in both cases the background of the strings extends to the screen limit and therefore is not limited to the text.

The string that I'm using is:

%d %t %z \n Ship %2A° %02B' %02.3C" %D %03E° %02F' %02.3G" %H HDG %03.02a° HDT %03.02K HDM %03.02L COG %03.02J SOG %2.02I

In the image below, the OCPN is configured using the English language, and is working, but in the way described above.

Thank you

String with 2 lines, in English language, as an example. 

![Statusbar Background](https://user-images.githubusercontent.com/83961934/117664620-5ed2d780-b178-11eb-8e5b-b56f7ced4790.jpg)

Bellow same String with 3 lines, in English language, as an example: 

 %d      %t      %z \n Ship   %2A° %02B' %02.3C" %D      %03E° %02F' %02.3G" %H \n HDG   %03.02a°      HDT   %03.02K      HDM   %03.02L      COG %03.02J      SOG   %2.02I 

![Statusbar Background With 3 Lines](https://user-images.githubusercontent.com/83961934/117664616-5d091400-b178-11eb-80f3-39c2867cff42.jpg)

**Comment by rgleason** [comment]
This is related to locale issues, I believe, some of which are not yet addressed.

**Comment by rgleason** [comment]
I think it is fixed now.

**Comment by Carl-Port** [comment]
Thanks Rick and all the best
Fair winds, smooth seas and blue horizons...

**Comment by rgleason** [comment]
Carl-Port   There is a new version out now, that you can try. Can we please close this?  The OP original poster normally closes these.

**Comment by rgleason** [comment]
Please close this Carl, if it is fixed.
